# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bt_protocol_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'bt_protocol_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x62t_protocol_service.proto\x12\x0b\x62t.protocol\x1a\x1bgoogle/protobuf/empty.proto\"A\n\x0cQuoteRequest\x12\x12\n\nstart_date\x18\x01 \x01(\x05\x12\x10\n\x08\x65nd_date\x18\x02 \x01(\x05\x12\x0b\n\x03sid\x18\x03 \x03(\x0c\"\x1d\n\nArrowFrame\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x32\xc8\x04\n\nbtDataFeed\x12\x44\n\x0c\x43\x61lendarCall\x12\x19.bt.protocol.QuoteRequest\x1a\x17.bt.protocol.ArrowFrame0\x01\x12\x46\n\x0eInstrumentCall\x12\x19.bt.protocol.QuoteRequest\x1a\x17.bt.protocol.ArrowFrame0\x01\x12G\n\x0f\x44\x61ilyStreamCall\x12\x19.bt.protocol.QuoteRequest\x1a\x17.bt.protocol.ArrowFrame0\x01\x12\x46\n\x0eTickStreamCall\x12\x19.bt.protocol.QuoteRequest\x1a\x17.bt.protocol.ArrowFrame0\x01\x12G\n\x0f\x43loseStreamCall\x12\x19.bt.protocol.QuoteRequest\x1a\x17.bt.protocol.ArrowFrame0\x01\x12L\n\x14\x41\x64justmentStreamCall\x12\x19.bt.protocol.QuoteRequest\x1a\x17.bt.protocol.ArrowFrame0\x01\x12G\n\x0fRightStreamCall\x12\x19.bt.protocol.QuoteRequest\x1a\x17.bt.protocol.ArrowFrame0\x01\x12;\n\tHeartBeat\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bt_protocol_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUOTEREQUEST']._serialized_start=71
  _globals['_QUOTEREQUEST']._serialized_end=136
  _globals['_ARROWFRAME']._serialized_start=138
  _globals['_ARROWFRAME']._serialized_end=167
  _globals['_BTDATAFEED']._serialized_start=170
  _globals['_BTDATAFEED']._serialized_end=754
# @@protoc_insertion_point(module_scope)
